//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShopOnline.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public string UrlImage { get; set; }
        public Nullable<System.Guid> NewsCategoryId { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescriptions { get; set; }
        public Nullable<System.DateTime> TopHot { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
