//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShopOnline.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Code { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public string UrlImage { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<bool> IncludeVAT { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.Guid> ProductCategoryId { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescriptions { get; set; }
        public Nullable<bool> TopHot { get; set; }
        public Nullable<bool> IsNormalProduct2 { get; set; }
        public Nullable<bool> IsNormalProduct1 { get; set; }
        public Nullable<bool> IsNewProduct { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
